app:
  replicas: 1
  name: usermgmt-service-ms
  configPath: /app/config
  port: 8085


configMap:
  name: usermgmt-service-config

image:
  repository: abw12/usermgmt-service-ms # update image
  tag: v3


postgres:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  host: db-postgresql-blr1-67863-do-user-15872635-0.c.db.ondigitalocean.com
  port: 25061
  db: absolutehealth
