apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  # ... other specs ...
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_LOCATION
              value: "file:{{ .Values.app.configPath }}/"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: psql-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.app.configPath }}
          ports:
            - containerPort: {{ .Values.app.port }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name }}
